{% set version = "3.9.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-deriv
  version: {{ version|replace("-", "_") }}

source:
  fn: Deriv_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Deriv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Deriv/Deriv_{{ version }}.tar.gz
  sha256: bc4fa2e67c75d6513d35555af9a0a0a36df33ba80a54835f3a74bc6582a89842

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('Deriv')"           # [not win]
    - "\"%R%\" -e \"library('Deriv')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Deriv
  license: GPL (>= 3)
  summary: R-based solution for symbolic differentiation. It admits user-defined function as
    well as function substitution in arguments of functions to be differentiated. Some
    symbolic simplification is part of the work.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
